### ISSUE TITLE
Seer 2.8.0 plays non-sense

### ISSUE THREAD

**Issue by achimste** [connormcmonigle/seer-nnue#189]
Hi Connor,

i tried the latest 2.8.0 of Seer on my Win10 machine (i7 with AVX512). No matter what binary a try, the engine plays random moves. The score output only display "info .. score 0.00 ..."

This did not happen in a previous version. If I remember correctly I used 2.6 before and there things worked fine.

Any idea?

Regards
Achim

**Comment by connormcmonigle** [comment]
Hello Achim,

Could you check your configured UCI options and validate that all the UCI options are set to the default values? Between Seer 2.6.0 and Seer 2.8.0, an additional `QuantizedWeights` UCI option was introduced which defaults to `EMBEDDED` whilst the old `Weights` UCI option now defaults to `UNUSED` as only the `QuantizedWeights` are embedded in the binary. My suspicion is that you've not updated the UCI option configuration when updating from 2.6.0.

Thanks for your interest,
Connor

**Comment by achimste** [comment]
Hello Connor,

Thank you! That solved the problem.

Achim
