### ISSUE TITLE
NN files for Seer ?

### ISSUE THREAD

**Issue by tissatussa** [connormcmonigle/seer-nnue#3]
hi,

one of your assets is the file "save.bin" which is a NN weight file .. somewhere i read that several types of NN weight files exist and Seer uses its own type, derived from NNUE.

where can i get other / newest seer .bin files ?
how do they differ ?

**Comment by connormcmonigle** [comment]
Hello,

The "save.bin" weights file asset released with v1.2.1 is the newest weights file and is the only weights file supported at this time.

In a week or so by my estimation, v1.3 should be ready for release which will incorporate a new set of weights and some improvements to the model architecture.

**Comment by tissatussa** [comment]
Thanks for this info.  How can a difference between NN files be tested ?  Do test positions exist ?  I read that different NN files have "different playing styles" but i have no clue how to determine that ..

**Comment by connormcmonigle** [comment]
Sorry, I'm not sure I follow exactly what you're asking.

Seer is incompatible with other engines' weights files as the model architecture used in Seer differs substantially from Stockfish/Rubi/Igel etc. Therefore, the weights are necessarily different from those used in other engines.

Playing style is quite a subjective notion. However, there exist utilities such as SIMEX which attempt to quantify similarity in playing style. Such utilities rely on a set of test positions. Seer's search is also original and, therefore, isolating differences in playing style originating from the evaluation function is nontrivial.

Hopefully this helps,
Connor
